[package]
name = "interactive"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2021"
publish = false

[dependencies]
bincode = "1"
serde = { version = "1", features = ["derive"]}
differential-dataflow = { path = "../" }
differential-dogs3 = { path = "../dogsdogsdogs" }
timely = { workspace = true }
#timely = { path = "../../timely-dataflow/timely", features = ["bincode"] }
