[package]
name = "interactive"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2021"
publish = false

[dependencies]
bincode = "1"
serde = { version = "1", features = ["derive"]}
differential-dataflow = { workspace = true }
differential-dogs3 = { path = "../dogsdogsdogs" }
timely = { workspace = true }
