[workspace]
# disable the changelog for all packages
changelog_update = false
release = false

[[package]]
name = "differential-dataflow"
release = true
# enable the changelog for this package
changelog_update = true
# set the path of the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"

[[package]]
name = "differential-dogs3"
release = true
# enable the changelog for this package
changelog_update = true
# set the path of the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"
