[package]
name = "degr_dist"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2021"
publish = false

[dependencies]
timely = { workspace = true }
differential-dataflow = { workspace = true }
dd_server = { path = "../../" }

[lib]
crate-type = ["dylib"]
