name: "Test build against Timely master"
on:
  workflow_dispatch:
  schedule:
    - cron: '38 3 * * *'

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu
        toolchain:
          - stable
    name: cargo test on ${{ matrix.os }}, rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Cargo patch Timely master
        run: |
          cat >> Cargo.toml <<EOF
          [patch.crates-io]
          timely = { git = "https://github.com/TimelyDataflow/timely-dataflow" }
          EOF
      - name: Cargo upgrade
        run: |
          cargo install cargo-edit
          cargo upgrade -p timely --incompatible
      - name: Cargo check against Timely master
        run: cargo check --all-targets
      - name: Cargo test against Timely master
        run: cargo test

  notify:
    name: Notify failed build
    if: failure() && github.event.pull_request == null
    needs: [tests]
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      # We need to checkout the repository to access the issue template
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: ${{ github.workflow }}
          REPO_SLUG: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          MENTION: '@frankmcsherry, @antiguru'
        with:
          filename: '.github/create-issue-on-failure.md'
          update_existing: true
          search_existing: open
